# BASE UI
ColorColumn: '- black1'
Conceal: ''
Cursor: ''
CursorIM: ''
CursorColumn: '- black1'
CursorLine: '- black1'
CursorLineNr: 'blue2 -'
Directory: 'blue1 -'
DiffAdd: '- green2'
DiffChange: '- blue2'
DiffDelete: 'red1 red2'
DiffText: '- - r'
ErrorMsg: 'red1 - r'
VertSplit: 'bg bg'
Folded: 'white1 black1'
FoldColumn: 'white1 black1'
SignColumn: 'black2 bg'
IncSearch: 'fg bg br'
LineNr: 'black2 -'
MatchParen: 'red1 - b'
ModeMsg: ''
MoreMsg: ''
NonText: 'black2'
Normal: 'fg bg'
PMenu: 'black2 blue1'
PMenuSel: 'blue1 green2'
PmenuSbar: 'blue1 blue1'
PmenuThumb: 'green2 green2'
Question: 'green2 -'
Search: 'fg - ub'
SpecialKey: 'black2'
SpellBad: 'red1'
SpellLocal: 'yellow1'
SpellCap: 'yellow2'
SpellRare: 'blue1'
StatusLine: 'bg fg b'
StatusLineNC: 'bg white1'
TabLine: 'white2 black2'
TabLineFill: '- black2'
TabLineSel: 'green2 - b'
Title: 'blue2 - b'
Visual: '- blue1 b'
VisualNOS: '- blue1 b'
WarningMsg: 'red1 -'
WildMenu: 'bg green2 b'
# BASE SYNTAX
Comment: 'white1'
Constant: ''
String: '' # Constant
Character: '' # Constant
Boolean: '' # Constant
Number: '' # Constant
Float: '' # Constant
Identifier: ''
Function: '' # Identifier
Statement: ''
Conditional: '' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: '' # Statement
Keyword: '' # Statement
Exception: '' # Statement
PreProc: ''
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: ''
StorageClass: '' # Type
Structure: '' # Type
Typedef: '' # Type
Special: ''
SpecialChar: '' # Special
Tag: '' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: ''
Todo: ''
